name: Deploy Project to Surge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Intalling Node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    
    # Step two Install Surge
    - name: Intalling Surge
      run: npm install --global surge
    
    # Deploy App To Surge
    - name: Deploy Project to Surge
      run: surge ./ fayyaz_jsprojects.surge.sh --token ${{ secrets.SURGE_TOKEN }} 
       
